# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    release:
      - step:
          script: # Modify the commands below to build your repository.
            - npm cache clean --force
            - npm install
            - npm run build:prod
            - pipe: atlassian/firebase-deploy:0.3.0
              variables:
                FIREBASE_TOKEN: "$FIREBASE_TOKEN_CI"
                PROJECT_ID: "$PROJECT_ID"
